export const RESET_BURGER = 'RESET_BURGER';
export const SWAP_INGREDIENTS = 'SWAP_INGREDIENTS';
export const CHANGE_BURGER_BUN = 'CHANGE_BURGER_BUN';
export const UPDATE_BURGER_ORDER = 'UPDATE_BURGER_ORDER';
export const ADD_BURGER_INDREDIENT = 'ADD_BURGER_INDREDIENT'; 
export const REMOVE_BURGER_INGREDIENT = 'REMOVE_BURGER_INGREDIENT';