export const INGREDIENT_REQUEST_FAIL = 'INGREDIENT_REQUEST_FAIL';
export const INGREDIENT_REQUEST_PENDING = 'INGREDIENT_REQUEST_PENDING';
export const INGREDIENT_REQUEST_SUCCESS = 'INGREDIENT_REQUEST_SUCCESS';

