export const OPEN_ORDER_POPUP = 'OPEN_ORDER_POPUP';
export const CLOSE_ORDER_POPUP = 'CLOSE_ORDER_POPUP';
export const ORDER_REQUEST_PENDING = 'ORDER_REQUEST_PENDING';
export const ORDER_REQUEST_FAIL = 'ORDER_REQUEST_FAIL';