export const OPEN_INSPECTED_INGREDIENT = 'OPEN_INSPECTED_INGREDIENT';
export const CLOSE_INSPECTED_INGREDIENT = 'CLOSE_INSPECTED_INGREDIENT';

export const OPEN_ORDER_POPUP = 'OPEN_ORDER_POPUP';
export const CLOSE_ORDER_POPUP = 'CLOSE_ORDER_POPUP';
export const ORDER_REQUEST_PENDING = 'ORDER_REQUEST_PENDING';
export const ORDER_REQUEST_FAIL = 'ORDER_REQUEST_FAIL';

export const OPEN_HEADER_POPUP = 'OPEN_HEADER_POPUP';
export const CLOSE_HEADER_POPUP = 'CLOSE_HEADER_POPUP';