// Constructor
export const RESET_BURGER: 'RESET_BURGER' = 'RESET_BURGER';
export const SWAP_INGREDIENTS: 'SWAP_INGREDIENTS' = 'SWAP_INGREDIENTS';
export const CHANGE_BURGER_BUN: 'CHANGE_BURGER_BUN' = 'CHANGE_BURGER_BUN';
export const ADD_BURGER_INDREDIENT: 'ADD_BURGER_INDREDIENT' = 'ADD_BURGER_INDREDIENT';  
export const REMOVE_BURGER_INGREDIENT: 'REMOVE_BURGER_INGREDIENT' = 'REMOVE_BURGER_INGREDIENT';

// Feed
export const FEED_REQUEST_FAIL: 'FEED_REQUEST_FAIL' =  'FEED_REQUEST_FAIL';
export const FEED_REQUEST_SUCCESS: 'FEED_REQUEST_SUCCESS' = 'FEED_REQUEST_SUCCESS';
export const FEED_REQUEST_PENDING: 'FEED_REQUEST_PENDING' = 'FEED_REQUEST_PENDING';

// Ingredients

export const INGREDIENT_REQUEST_FAIL: 'INGREDIENT_REQUEST_FAIL' = 'INGREDIENT_REQUEST_FAIL';
export const INGREDIENT_REQUEST_PENDING: 'INGREDIENT_REQUEST_PENDING' = 'INGREDIENT_REQUEST_PENDING';
export const INGREDIENT_REQUEST_SUCCESS: 'INGREDIENT_REQUEST_SUCCESS' = 'INGREDIENT_REQUEST_SUCCESS';

// Order

export const OPEN_ORDER_POPUP: 'OPEN_ORDER_POPUP' = 'OPEN_ORDER_POPUP';
export const CLOSE_ORDER_POPUP: 'CLOSE_ORDER_POPUP' = 'CLOSE_ORDER_POPUP';
export const ORDER_POPUP_REQUEST_FAIL: 'ORDER_POPUP_REQUEST_FAIL' = 'ORDER_POPUP_REQUEST_FAIL';
export const ORDER_POPUP_REQUEST_PENDING: 'ORDER_POPUP_REQUEST_PENDING' = 'ORDER_POPUP_REQUEST_PENDING';

// Socket

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';